# Generated by Django 4.2.2 on 2023-06-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetrolPumpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.CharField(max_length=50),
        ),
    ]
