# Generated by Django 4.2.2 on 2023-06-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetrolPumpApp', '0002_alter_employee_birth_date_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_company',
            field=models.CharField(max_length=100),
        ),
    ]
