# Generated by Django 4.2.2 on 2023-06-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetrolPumpApp', '0003_alter_machine_machine_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.CharField(max_length=50)),
                ('slot_time', models.CharField(max_length=50)),
                ('slot_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetrolPumpApp.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetrolPumpApp.owner')),
            ],
        ),
    ]
