# Generated by Django 4.2.2 on 2023-06-21 03:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetrolPumpApp', '0004_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(default=datetime.datetime(2023, 6, 21, 9, 23, 12, 156583), max_length=50)),
                ('feddback_message', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetrolPumpApp.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetrolPumpApp.owner')),
            ],
        ),
    ]
