# Generated by Django 4.2.2 on 2023-06-21 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetrolPumpApp', '0005_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feddback_message',
            new_name='feedback_message',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 9, 25, 26, 334086), max_length=50),
        ),
    ]
