# Generated by Django 4.2.2 on 2023-06-21 04:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetrolPumpApp', '0006_rename_feddback_message_feedback_feedback_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 10, 28, 54, 138020), max_length=50),
        ),
        migrations.CreateModel(
            name='PUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=20)),
                ('date_of_apply', models.DateField(default=datetime.datetime(2023, 6, 21, 10, 28, 54, 139017))),
                ('date_of_issue', models.DateField(default=None)),
                ('date_of_expiry', models.DateField(default=None)),
                ('carbon_monoxide', models.FloatField(default=0.0)),
                ('hydro_carbon', models.FloatField(default=0.0)),
                ('methane_hdc', models.FloatField(default=0.0)),
                ('reactive_hc', models.FloatField(default=0.0)),
                ('charges', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetrolPumpApp.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetrolPumpApp.owner')),
            ],
        ),
    ]
