# Generated by Django 4.2.2 on 2023-06-21 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetrolPumpApp', '0007_alter_feedback_feedback_date_puc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puc',
            old_name='methane_hdc',
            new_name='methane_hc',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 11, 13, 57, 630244), max_length=50),
        ),
        migrations.AlterField(
            model_name='puc',
            name='date_of_apply',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 11, 13, 57, 631241)),
        ),
    ]
