# Generated by Django 4.2.2 on 2023-06-21 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetrolPumpApp', '0008_rename_methane_hdc_puc_methane_hc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 11, 19, 56, 229193), max_length=50),
        ),
        migrations.AlterField(
            model_name='puc',
            name='date_of_apply',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 11, 19, 56, 229193)),
        ),
        migrations.AlterField(
            model_name='puc',
            name='date_of_expiry',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='puc',
            name='date_of_issue',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
