# Generated by Django 4.2.2 on 2023-06-23 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetrolPumpApp', '0009_alter_feedback_feedback_date_alter_puc_date_of_apply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 16, 55, 40, 635672), max_length=50),
        ),
        migrations.AlterField(
            model_name='puc',
            name='date_of_apply',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 16, 55, 40, 636695)),
        ),
    ]
